#!/usr/bin/env python
"""basic qubole functionality
"""

import json
import os

import requests
import fire


class Qubole:
    """Basic qubole wrapper"""
    def __init__(self):
        try:
            self.token = os.environ["QUBOLE_TOKEN"]
        except KeyError:
            print("Missing Qubole token")
        self.api = "https://us.qubole.com/api/v1.3/clusters/{CLUSTERID}/state"

    def state(self, cluster=19436, full=False):
        """Finds out the state of the cluster"""
        response = requests.get(
            url=self.api.format(CLUSTERID=cluster),
            headers={'X-AUTH-TOKEN': self.token}
        )

        values = json.loads(response.content)
        if full:
            print(values)
        else:
            if values["state"] == 'UP':
                print(f"Cluster {cluster} UP")
                state = True
            elif values["state"] == 'DOWN':
                print(f"Cluser {cluster} DOWN")
                state = False
            elif values["state"] == "PENDING":
                print(f"Cluster {cluster} PENDING")
                state = False
            else:
                print(f"Cluster {cluster} UNKNOWN")
                state = False
            return state

    def toggle(self, cluster):
        """Toggles the cluster on and off"""
        active = self.state(cluster)
        state = "start" if not active else "terminate"
        response = requests.put(
            url=self.api.format(CLUSTERID=cluster),
            headers={
                'X-AUTH-TOKEN': self.token,
                'Content-Type': 'application/json',
                'Accept': 'application/json',
            },
            data=json.dumps({"state": state})
        )
        print(response.content)


if __name__ == '__main__':
    fire.Fire(Qubole)
